import type { AIProvider, ChatRequest, ChatResult } from '../types.js'

/**
 * Offline mock provider. Needs no API key and makes no network call — it returns
 * a deterministic, clearly-labelled draft assembled from the prompt, so the full
 * drafting pipeline (context assembly → generate → editable draft → preserve
 * edits) is testable and demoable with zero keys. Never billed, always available.
 */
export const mockAdapter: AIProvider = {
  id: 'mock',
  async generate(req: ChatRequest): Promise<ChatResult> {
    const userText = req.messages.filter((m) => m.role === 'user').map((m) => m.content).join('\n\n')
    // Pull the research context the drafting engine passed in, if any.
    const contextExcerpt = userText.slice(0, 1200)

    const text = [
      `> _Draft generated by the offline **Mock** provider — no API key needed._`,
      `> _Add a real provider key in Settings › AI Providers to draft with Claude, GPT, Gemini, or Grok._`,
      '',
      `## Draft`,
      '',
      `This is a placeholder draft produced from the ${req.messages.length} message(s) of research context supplied to the AI engine. A real provider would synthesise the notes, data, and references below into publication-quality prose.`,
      '',
      `### What the engine received`,
      '',
      '```',
      contextExcerpt || '(no context supplied)',
      '```',
      '',
      `_Model: ${req.model} · max tokens: ${req.maxTokens ?? 4096}_`,
    ].join('\n')

    // Small delay to mimic network latency for realistic UI behaviour.
    await new Promise((r) => setTimeout(r, 250))

    return {
      text,
      model: 'mock',
      finishReason: 'end_turn',
      usage: { inputTokens: userText.length, outputTokens: text.length },
    }
  },
}
